#281/testing/Adding cypress testing to CI pipeline

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -100,3 +100,40 @@ jobs:
 
       - name: Docker Build and Compose for deployment
         run: docker compose --env-file backend.env up -d --build
+
+      - name: Making sure Backend is running
+        run: |
+          for i in {1..30}; do
+            if curl -s http://localhost:8080/api/health > /dev/null; then
+              echo "Backend is running"
+              exit 0
+            fi
+            echo "Waiting..."
+            sleep 5
+          done
+          echo "Backend failed"
+          exit 1
+      - name: Making sure Frontend is running
+        run: |
+          for i in {1..30}; do
+            if curl -s http://localhost:5173 > /dev/null; then
+              echo "Frontend is running"
+              exit 0
+            fi
+            echo "Waiting..."
+            sleep 5
+          done
+          echo "Frontend failed"
+          exit 1
+
+      - name: Cypress Installation
+        working-directory: ./visual-compiler/frontend
+        run: npm install cypress --save-dev
+
+      - name: Run Cypress
+        working-directory: ./visual-compiler/frontend
+        run: npx cypress run
+
+      - name: Docker Compose Shut down
+        if: always()
+        run: docker compose down
